site_name: pgserviceparser documentation
theme:
  name: "material"
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
plugins:
  - mkdocstrings
markdown_extensions:
  - admonition
  - codehilite
nav:
  - Home: index.md
  - API:
      - Reference: api.md
      - Exceptions: exceptions.md
      - PGServiceParserWidget: pgserviceparser_widget.md
  - GUI: gui.md
